testing to work with JAGS
git-svn-id: file:///home/git/hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/CoGAPS@80748 bc3139a8-67e5-0310-9ffc-ced21a209358

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -581,7 +581,7 @@ ac_hostname=`(hostname || uname -n) 2>/dev/null | sed 1q`
 #
 # Initializations.
 #
-ac_default_prefix=/usr/local
+ac_default_prefix=/usr/local/GAPS-JAGS
 ac_clean_files=
 ac_config_libobj_dir=.
 LIBOBJS=
@@ -594,7 +594,7 @@ SHELL=${CONFIG_SHELL-/bin/sh}
 # Identity of this package.
 PACKAGE_NAME='CoGAPS'
 PACKAGE_TARNAME='CoGAPS'
-PACKAGE_VERSION='1.0.2'
+PACKAGE_VERSION='1.0.3'
 PACKAGE_STRING='CoGAPS 1.3.1'
 PACKAGE_BUGREPORT=''
 
@@ -636,9 +636,9 @@ ac_includes_default="\
 
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
-JAGS_MODULES
-JAGS_LIB
-JAGS_INCLUDE
+GAPSJAGS_MODULES
+GAPSJAGS_LIB
+GAPSJAGS_INCLUDE
 ac_ct_CC
 CFLAGS
 CC
@@ -1890,7 +1890,7 @@ fi
 
 
 #Set optional include path with option --with-jags-include or
-#environment variable JAGS_INCLUDE
+#environment variable GAPSJAGS_INCLUDE
 
 
 # Check whether --with-jags-include was given.
@@ -1899,15 +1899,15 @@ if test "${with_jags_include+set}" = set; then
 fi
 
 if test  -n "$jags_include_path"  ; then
-   JAGS_INCLUDE=${jags_include_path}
+   GAPSJAGS_INCLUDE=${jags_include_path}
 else
-   if test  -z "${JAGS_INCLUDE}"  ; then
+   if test  -z "${GAPSJAGS_INCLUDE}"  ; then
       if test  "$prefix" = "NONE" ; then
-         { { $as_echo "$as_me:$LINENO: error: \"Location of JAGS headers not defined. Use configure arg '--with-jags-include' or environment variable 'JAGS_INCLUDE'\"" >&5
-$as_echo "$as_me: error: \"Location of JAGS headers not defined. Use configure arg '--with-jags-include' or environment variable 'JAGS_INCLUDE'\"" >&2;}
+         { { $as_echo "$as_me:$LINENO: error: \"Location of JAGS headers not defined. Use configure arg '--with-jags-include' or environment variable 'GAPSJAGS_INCLUDE'\"" >&5
+$as_echo "$as_me: error: \"Location of JAGS headers not defined. Use configure arg '--with-jags-include' or environment variable 'GAPSJAGS_INCLUDE'\"" >&2;}
    { (exit 1); exit 1; }; }
       else
-         JAGS_INCLUDE=${prefix}/include/GAPS-JAGS
+         GAPSJAGS_INCLUDE=${prefix}/include/GAPS-JAGS
       fi
    fi
 fi
@@ -1919,7 +1919,7 @@ ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ex
 ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 OCPPFLAGS=${CPPFLAGS}
-CPPFLAGS=-I${JAGS_INCLUDE}
+CPPFLAGS=-I${GAPSJAGS_INCLUDE}
 ac_ext=cpp
 ac_cpp='$CXXCPP $CPPFLAGS'
 ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3293,9 +3293,9 @@ if test "x$ac_cv_header_Console_h" = x""yes; then
 else
   { { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
 $as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
-{ { $as_echo "$as_me:$LINENO: error: \"Problem with header file ${JAGS_INCLUDE}/Console.h \"
+{ { $as_echo "$as_me:$LINENO: error: \"Problem with header file ${GAPSJAGS_INCLUDE}/Console.h \"
 See \`config.log' for more details." >&5
-$as_echo "$as_me: error: \"Problem with header file ${JAGS_INCLUDE}/Console.h \"
+$as_echo "$as_me: error: \"Problem with header file ${GAPSJAGS_INCLUDE}/Console.h \"
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }; }
 fi
@@ -3330,7 +3330,7 @@ $as_echo "$as_me: error: \"R_HOME is not defined\"" >&2;}
 fi
 
 #Set optional library path with option --with-jags-lib or
-#environment variable JAGS_LIBS
+#environment variable GAPSJAGS_LIBS
 
 
 # Check whether --with-jags-lib was given.
@@ -3339,15 +3339,15 @@ if test "${with_jags_lib+set}" = set; then
 fi
 
 if test  -n "$jags_lib_path"  ; then
-   JAGS_LIB=$jags_lib_path
+   GAPSJAGS_LIB=$jags_lib_path
 else
-   if test  -z "${JAGS_LIB}"  ; then
+   if test  -z "${GAPSJAGS_LIB}"  ; then
       if test  "${prefix}" = "NONE"  ; then
-         { { $as_echo "$as_me:$LINENO: error: \"Location of JAGS library not defined. Use configure arg '--with-jags-lib' or environment variable 'JAGS_LIB'\"" >&5
-$as_echo "$as_me: error: \"Location of JAGS library not defined. Use configure arg '--with-jags-lib' or environment variable 'JAGS_LIB'\"" >&2;}
+         { { $as_echo "$as_me:$LINENO: error: \"Location of JAGS library not defined. Use configure arg '--with-jags-lib' or environment variable 'GAPSJAGS_LIB'\"" >&5
+$as_echo "$as_me: error: \"Location of JAGS library not defined. Use configure arg '--with-jags-lib' or environment variable 'GAPSJAGS_LIB'\"" >&2;}
    { (exit 1); exit 1; }; }
       else
-         JAGS_LIB=${prefix}/lib
+         GAPSJAGS_LIB=${prefix}/lib
       fi
    fi
 fi
@@ -3359,7 +3359,7 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-LDFLAGS=-L${JAGS_LIB}
+LDFLAGS=-L${GAPSJAGS_LIB}
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4118,8 +4118,8 @@ _ACEOF
   LIBS="-ljags $LIBS"
 
 else
-  { { $as_echo "$as_me:$LINENO: error: \"Cannot load JAGS library in ${JAGS_LIB}\"" >&5
-$as_echo "$as_me: error: \"Cannot load JAGS library in ${JAGS_LIB}\"" >&2;}
+  { { $as_echo "$as_me:$LINENO: error: \"Cannot load JAGS library in ${GAPSJAGS_LIB}\"" >&5
+$as_echo "$as_me: error: \"Cannot load JAGS library in ${GAPSJAGS_LIB}\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4133,7 +4133,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 LDFLAGS=${OLDFLAGS}
 
 #Finally, set optional module directory using --with-jags-modules or
-#environment variable JAGS_MODULES
+#environment variable GAPSJAGS_MODULES
 
 
 # Check whether --with-jags-modules was given.
@@ -4142,13 +4142,13 @@ if test "${with_jags_modules+set}" = set; then
 fi
 
 if test  -n "$jags_mod_path"  ; then
-   JAGS_MODULES=$jags_mod_path
+   GAPSJAGS_MODULES=$jags_mod_path
 else
-   if test  -z "${JAGS_MODULES}"  ; then
-      JAGS_MODULES=${JAGS_LIB}/JAGS/modules-${PACKAGE_VERSION}
-      if test ! -d ${JAGS_MODULES} ; then
-         { { $as_echo "$as_me:$LINENO: error: \"JAGS module directory ${JAGS_MODULES} does not exist.\"" >&5
-$as_echo "$as_me: error: \"JAGS module directory ${JAGS_MODULES} does not exist.\"" >&2;}
+   if test  -z "${GAPSJAGS_MODULES}"  ; then
+      GAPSJAGS_MODULES=${GAPSJAGS_LIB}/JAGS/modules-${PACKAGE_VERSION}
+      if test ! -d ${GAPSJAGS_MODULES} ; then
+         { { $as_echo "$as_me:$LINENO: error: \"JAGS module directory ${GAPSJAGS_MODULES} does not exist.\"" >&5
+$as_echo "$as_me: error: \"JAGS module directory ${GAPSJAGS_MODULES} does not exist.\"" >&2;}
    { (exit 1); exit 1; }; }
       fi
    fi
